import json
import os

class ReadJson():
    def __init__(self):
        file = open(os.getcwd()+'/values.json', "r")
        fj = json.loads(file.read())
        self.fj_lang = fj["en"]
        file.close()

    def read_project_name(self):
        return self.fj_lang["PROJECT_NAME"]
    def read_server_name(self):
        return self.fj_lang["SERVER_NAME"]
    def read_server_host(self):
        return self.fj_lang["SERVER_HOST"]
    def read_sentry_dns(self):
        return self.fj_lang["SENTRY_DNS"]
    def read_postgres_server(self):
        return self.fj_lang["POSTGRES_SERVER"]
    def read_postgres_user(self):
        return self.fj_lang["POSTGRES_USER"]
    def read_postgres_password(self):
        return self.fj_lang["POSTGRES_PASSWORD"]
    def read_postgres_db(self):
        return self.fj_lang["POSTGRES_DB"]
    def read_postgres_uri(self):
        return self.fj_lang["POSTGRES_URI"]
    def read_nav_home_words(self):
        return self.fj_lang["HOME_PAGE"]["NAVIGATION_BAR"]
    def read_title_home_word(self):
        return self.fj_lang["HOME_PAGE"]["TITLE"]
    def read_addr_home_images(self):
        return self.fj_lang["HOME_PAGE"]["IMAGES"]
    def read_description_home_sences(self):
        return self.fj_lang["HOME_PAGE"]["DESCRIPTIONS"]
    def read_comment_home_cards(self):
        return self.fj_lang["HOME_PAGE"]["IMAGES_COMMENT"], self.fj_lang["HOME_PAGE"]["NAMES_COMMENT"], self.fj_lang["HOME_PAGE"]["DESCRIPTIONS_COMMENT"]
    def read_footer_home(self):
        return self.fj_lang["HOME_PAGE"]["FOOTER"]
    def read_title_signup_word(self):
        return self.fj_lang["SIGNUP"]["TITLE"]
    def read_input_signup_words(self):
        return self.fj_lang["SIGNUP"]["INPUT_LIST"]
    def read_signin_url(self):
        return self.fj_lang["SIGNIN_URL"]
    def read_signup_url(self):
        return self.fj_lang["SIGNUP_URL"]
    def read_home_url(self):
        return self.fj_lang["HOME_URL"]
    def read_title_signin_word(self):
        return self.fj_lang["LOGIN"]["TITLE"]
    def read_input_signin_words(self):
        return self.fj_lang["LOGIN"]["INPUT_LIST"]
    def read_title_of_profile(self):
        return self.fj_lang["PROFILE"]["TITLE"]
    def read_profile_fname(self):
        return self.fj_lang["PROFILE"]["FNAME"]
    def read_profile_lname(self):
        return self.fj_lang["PROFILE"]["LNAME"]
    def read_profile_resume(self):
        return self.fj_lang["PROFILE"]["RESUME"]
    def read_profile_burn(self):
        return self.fj_lang["PROFILE"]["BURN"]
    def read_profile_wa(self):
        return self.fj_lang["PROFILE"]["WALLETADDRESS"]
    def read_profile_bio(self):
        return self.fj_lang["PROFILE"]["BIO"]
    def read_profile_addr(self):
        return self.fj_lang["PROFILE"]["ADDRESS"]
    def read_profile_city(self):
        return self.fj_lang["PROFILE"]["CITY"]
    def read_profile_country(self):
        return self.fj_lang["PROFILE"]["COUNTRY"]
    def read_profile_img_prof(self):
        return self.fj_lang["PROFILE"]["IMGADDRESS"]
    def read_profile_final_proj_dev_title(self):
        return self.fj_lang["PROFILE"]["FINAL_PROJECT_DEVELOPED"]
    def read_profile_name(self):
        return self.fj_lang["PROFILE"]["NAME"]
    def read_profile_start_date(self):
        return self.fj_lang["PROFILE"]["START_DATE"]
    def read_profile_cost(self):
        return self.fj_lang["PROFILE"]["COST"]
    def read_profile_end_date(self):
        return self.fj_lang["PROFILE"]["END_DATE"]
    def read_profile_describe(self):
        return self.fj_lang["PROFILE"]["DESCRIBE"]
    def read_profile_proj_dev_title(self):
        return self.fj_lang["PROFILE"]["PROJECTS_ARE_DEVELOPING"]
    def read_profile_proj_def_title(self):
        return self.fj_lang["PROFILE"]["PROJECT_DEFINED"]
    def read_profile_proj_fin_def_title(self):
        return self.fj_lang["PROFILE"]["FINAL_PROJECT_DEFINED"]
    def read_title_of_project(self):
        return self.fj_lang["PROJECT"]["TITLE"]
    def read_api_prev_url(self):
        return self.fj_lang["API_PREV_URL"]
    def read_tabs_headers(self):
        return self.fj_lang["PROJECT"]["TABSHEADERS"]
    def read_name_of_project_lancer(self):
        return self.fj_lang["PROJECT"]["NAME_LANCER"]
    def read_description_of_project_lancer(self):
        return self.fj_lang["PROJECT"]["DESCRIPTION_LANCER"]
    def read_deadline_of_project_lancer(self):
        return self.fj_lang["PROJECT"]["DATE_FINISH_LANCER"]
    def read_file_of_project_lancer(self):
        return self.fj_lang["PROJECT"]["FILE_LANCER"]
    def read_cost_of_project_lancer(self):
        return self.fj_lang["PROJECT"]["COST_LANCER"]
    def read_img_of_project_lancer(self):
        return self.fj_lang["PROJECT"]["IMG_LANCER"]
    def read_item_project_name(self):
        return self.fj_lang["PROJECT"]["NAME"]
    def read_item_project_end_date(self):
        return self.fj_lang["PROJECT"]["EDATE"]
    def read_item_project_cost(self):
        return self.fj_lang["PROJECT"]["COST"]
    def read_title_of_upload_project_page(self):
        return self.fj_lang["UPLOAD"]["TITLE"]
    def read_placeholder_of_upload_project_page(self):
        return self.fj_lang["UPLOAD"]["UPLOAD_PROJECT"]
    def read_submit_of_upload_project_page(self):
        return self.fj_lang["UPLOAD"]["SUBMIT"]
    def read_present_project_title(self):
        return self.fj_lang["PRESENT_PROJECT"]["TITLE"]
    def read_submit_of_present_project_page(self):
        return self.fj_lang["PRESENT_PROJECT"]["SUBMIT"]
    def read_common_of_present_project_page(self):
        return self.fj_lang["PRESENT_PROJECT"]["COMMON"]
    def read_download_of_present_project_page(self):
        return self.fj_lang["PRESENT_PROJECT"]["DOWNLOAD"]
    def read_ombre_ip(self):
        return self.fj_lang["OMBRE"]["IP"]
    def read_ombre_port(self):
        return self.fj_lang["OMBRE"]["PORT"]
    def read_ombre_wallet_address(self):
        return self.fj_lang["OMBRE"]["WALLET_ADDRESS"]
    def read_ombre_balance(self):
        return self.fj_lang["OMBRE"]["BALANCE"]
    def read_ombre_title(self):
        return self.fj_lang["OMBRE"]["TITLE"]
    def read_ombre_recieve_address(self):
        return self.fj_lang["OMBRE"]["REC_ADDR"]
    def read_ombre_recieve_address_enter(self):
        return self.fj_lang["OMBRE"]["ENTER_REC_ADDR"]
    def read_ombre_amount(self):
        return self.fj_lang["OMBRE"]["AMOUNT"]
    def read_ombre_amount_enter(self):
        return self.fj_lang["OMBRE"]["ENTER_AMOUNT"]